import './globals.css';

import { enUS } from '@clerk/localizations';
import { ClerkProvider } from '@clerk/nextjs';
import { shadcn } from '@clerk/themes';
import { ThemeProvider } from '@repo/ui/components/theme-provider';
import { Toaster } from '@repo/ui/components/ui/sonner';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { type Locale, NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import type { PropsWithChildren } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getLocalizationResource = (locale: Locale) => {
  switch (locale) {
    case 'en-US':
    default:
      return enUS;
  }
};

export default async function Layout({ children }: Readonly<PropsWithChildren>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <ClerkProvider
      localization={getLocalizationResource(locale)}
      appearance={{
        baseTheme: shadcn,
      }}
    >
      <html lang={locale} suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <NextIntlClientProvider messages={messages}>
            <NuqsAdapter>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                {children}
                <Toaster position="bottom-center" />
              </ThemeProvider>
            </NuqsAdapter>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
