packages:
  - apps/**
  - packages/**

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
