export const ErrorCodes = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  SHARED_DTO_VALIDATION_ERROR: 'SHARED_DTO_VALIDATION_ERROR',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
};

export const MessageAction = {
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  UPDATE: 'UPDATE',
  UPSERT: 'UPSERT',
  CREATE_MANY: 'CREATE_MANY',
  DELETE_MANY: 'DELETE_MANY',
  UPDATE_MANY: 'UPDATE_MANY',
  FIND_MANY: 'FIND_MANY',
  FIND_UNIQUE: 'FIND_UNIQUE',
  GET_INDEX: 'GET_INDEX',
  ADD_DOCUMENTS: 'ADD_DOCUMENTS',
  DELETE_DOCUMENTS: 'DELETE_DOCUMENTS',
  UPDATE_DOCUMENTS: 'UPDATE_DOCUMENTS',
  SEARCH_DOCUMENTS: 'SEARCH_DOCUMENTS',
} as const;

export const MessageEntity = {
  CLERK: 'CLERK',
  CLERK_ROLE_MAPPER: 'CLERK_ROLE_MAPPER',
  CREDITS: 'CREDITS',
  LANGUAGE: 'LANGUAGE',
  MEILISEARCH: 'MEILISEARCH',
  ORGANIZATION: 'ORGANIZATION',
  ORGANIZATION_MEMBERSHIP: 'ORGANIZATION_MEMBERSHIP',
  PRISMA: 'PRISMA',
  RABBITMQ: 'RABBITMQ',
  REDIS_CACHE: 'REDIS_CACHE',
  SHARED: 'SHARED',
  USER: 'USER',
  WEBHOOK_EVENT: 'WEBHOOK_EVENT',
} as const;
