export const CLERK_CLIENT = 'CLERK_CLIENT';

export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_NOT_MEMBER_OF_CURRENT_ORGANIZATION: 'USER_IS_NOT_MEMBER_OF_CURRENT_ORGANIZATION',
  USER_NOT_IN_ORGANIZATION_CONTEXT: 'USER_NOT_IN_ORGANIZATION_CONTEXT',
  FAILED_SYNC_ORGANIZATION_MEMBERSHIP: 'FAILED_SYNC_ORGANIZATION_MEMBERSHIP',
};
